export const contactsConstants = {
    FETCH_CONTACTS_REQUEST: 'FETCH_CONTACTS_REQUEST',
    FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',
    FETCH_CONTACTS_FAILURE: 'FETCH_CONTACTS_FAILURE',
    FETCH_CONTACT_REQUEST: 'FETCH_CONTACT_REQUEST',
    FETCH_CONTACT_SUCCESS: 'FETCH_CONTACT_SUCCESS',
    FETCH_CONTACT_FAILURE: 'FETCH_CONTACT_FAILURE'
}
