export const userConstants = {
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

    FETCH_LOGIN_REQUEST: 'FETCH_LOGIN_REQUEST',
    FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',

    USERS_LOGOUT: 'USERS_LOGOUT'
}
